name: My Door Dash Workflow


on:
  push:           # every time you push new commits
    branches:
      - main
  workflow_dispatch:  # and manually from the Actions tab

jobs:
  door-dash:          # name of the job
    runs-on: ubuntu-latest   # GitHub provides an Ubuntu VM

    steps:
      - uses: actions/checkout@v4

      - name: Print greeting
        run: echo "👋 Hello from Jedha!"

      - name: Build Docker image
        run: |
          docker build -t my-app:${{ github.sha }} .
    
      - name: Start Docker container
        run: |
          docker run -d --name my-app-container -p 8090:8090 my-app:${{ github.sha }}

      - name: State of Docker container
        run: |
          sleep 5
          docker ps -a | grep my-app-container

      - name: Test 8090 endpoint
        run: |
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8090)
  
          echo "HTTP response code: $HTTP_CODE "
          if [ "$HTTP_CODE" -eq 200 ]; then
            echo "Endpoint OK (HTTP $HTTP_CODE)"
          else
            echo "Endpoint KO (HTTP $HTTP_CODE)"
            exit 1
          fi
      - name: Stop Docker container
        run: |
          docker stop my-app-container
          docker rm my-app-container